<a href="https://colab.research.google.com/github/hongocphuongnhu/TH_Deep_Learning/blob/main/TH_Deep_Tuan1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install numpy
import numpy as np

In [3]:
#Cau1, 2
a = np.random.randint(20, size = (3,3))
print (a)
print("Kiểm tra các phần tử khác 0 trong mảng: ",np.all(a))
print("Kiểm tra có tồn tại ít nhất một phần tử khác 0 trong mảng: ", np.any(a))

[[12  2 13]
 [ 5 17 15]
 [10  8 18]]
Kiểm tra các phần tử khác 0 trong mảng:  True
Kiểm tra có tồn tại ít nhất một phần tử khác 0 trong mảng:  True


In [5]:
#Cau3
#Mang1Chieu
arr1_1c = np.random.randint(20, size=(3, 3))
arr2_1c = np.random.randint(20, size=(3, 3))
print(np.greater(arr1_1c, arr2_1c))
print(np.greater_equal(arr1_1c, arr2_1c))
print(np.less(arr1_1c, arr2_1c))
print(np.less_equal(arr1_1c, arr2_1c))
#Mang2Chieu
arr1_2c = np.random.randint(20, size=(3, 3))
arr2_2c = np.random.randint(20, size=(3, 3))
print(np.greater(arr1_2c, arr2_2c))
print(np.greater_equal(arr1_2c, arr2_2c))
print(np.less(arr1_2c, arr2_2c))
print(np.less_equal(arr1_2c, arr2_2c))

[[False  True  True]
 [False  True False]
 [ True False False]]
[[False  True  True]
 [False  True False]
 [ True  True False]]
[[ True False False]
 [ True False  True]
 [False False  True]]
[[ True False False]
 [ True False  True]
 [False  True  True]]
[[False False  True]
 [ True False  True]
 [ True  True False]]
[[ True  True  True]
 [ True False  True]
 [ True  True False]]
[[False False False]
 [False  True False]
 [False False  True]]
[[ True  True False]
 [False  True False]
 [False False  True]]


In [7]:
#Cau4
ones_array = np.ones(10, dtype=int)
zeros_array = np.zeros(10, dtype=int)
fives_array = np.full(10,5, dtype=int)
combined_array = np.concatenate((ones_array, zeros_array, fives_array))
print(combined_array)

[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 5 5 5 5 5 5 5 5 5 5]


In [12]:
#Cau5: Tạo mảng số nguyên chẵn từ [30, 70]
c = np.arange(30, 71, 2)
print("Mảng số nguyên chẵn từ 30 đến 70:", c)

Mảng số nguyên chẵn từ 30 đến 70: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [13]:
#Cau6:
identity_matrix = np.identity(3, dtype=int)
print("Ma trận đơn vị 3x3:")
print(identity_matrix)

Ma trận đơn vị 3x3:
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [14]:
#Cau7:
random_array = np.random.randint(15, 56, size=10)
print("Mảng gốc:", random_array)
print("Các phần tử không bao gồm phần tử đầu và cuối:", random_array[1:-1])

Mảng gốc: [24 47 45 33 46 55 48 37 15 47]
Các phần tử không bao gồm phần tử đầu và cuối: [47 45 33 46 55 48 37 15]


In [15]:
#Cau8:
# Tạo mảng 20 phần tử ngẫu nhiên trong khoảng [0, 20]
my_array = np.random.randint(0, 21, size=20)
print("Mảng gốc:", my_array)
condition = (my_array >= 9) & (my_array <= 15)
my_array[condition] = -my_array[condition]

print("Mảng sau khi đổi dấu:", my_array)

Mảng gốc: [10 19 17  0  6  0  2  3 13  1 18  8 11 11  9  2  7 20  3 16]
Mảng sau khi đổi dấu: [-10  19  17   0   6   0   2   3 -13   1  18   8 -11 -11  -9   2   7  20
   3  16]


In [17]:
#Cau9
a = np.random.randint(10, 22, size=(3,4))
print(a)

[[16 10 12 16]
 [13 21 19 20]
 [18 15 12 16]]


In [18]:
#Cau10: Tạo ma trận 10x10 với các phần tử ở biên có giá trị 1 và các phần tử bên trong có giá trị 0

matrix_10x10 = np.zeros((10, 10), dtype=int)

# Đặt giá trị 1 cho các phần tử ở biên
matrix_10x10[0, :] = 1
matrix_10x10[-1, :] = 1
matrix_10x10[:, 0] = 1
matrix_10x10[:, -1] = 1

print("Ma trận 10x10 với biên là 1 và bên trong là 0:")
print(matrix_10x10)

Ma trận 10x10 với biên là 1 và bên trong là 0:
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [19]:
#Cau11: Tạo ma trận 5x5 với các phần tử ở đường chéo chính là 1, 2, 3, 4, 5
diagonal_elements = np.array([1, 2, 3, 4, 5])

# Sử dụng np.diag để tạo ma trận đường chéo từ mảng 1D
matrix_diagonal = np.diag(diagonal_elements)

print("Ma trận 5x5 với đường chéo chính là 1, 2, 3, 4, 5:")
print(matrix_diagonal)

Ma trận 5x5 với đường chéo chính là 1, 2, 3, 4, 5:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [20]:
#Cau12: Tạo mảng 3x3x3 và tính tổng theo mỗi dòng, mỗi cột

my_3d_array = np.random.randint(0, 21, size=(3, 3, 3))
print("Mảng 3x3x3:")
print(my_3d_array)

sum_along_rows = np.sum(my_3d_array, axis=2)
print("\nTổng theo 'dòng' (axis=2, tổng các cột trong mỗi 3x3 slice):")
print(sum_along_rows)

sum_along_columns = np.sum(my_3d_array, axis=1)
print("\nTổng theo 'cột' (axis=1, tổng các hàng trong mỗi 3x3 slice):")
print(sum_along_columns)

sum_along_depth = np.sum(my_3d_array, axis=0)
print("\nTổng theo 'sâu' (axis=0, tổng qua các slice 3x3):")
print(sum_along_depth)

Mảng 3x3x3:
[[[ 5  5  6]
  [20 19 20]
  [17  3  2]]

 [[ 1  7 12]
  [14  7 20]
  [ 8  8  6]]

 [[20  1  2]
  [ 9  3 18]
  [ 4  1  6]]]

Tổng theo 'dòng' (axis=2, tổng các cột trong mỗi 3x3 slice):
[[16 59 22]
 [20 41 22]
 [23 30 11]]

Tổng theo 'cột' (axis=1, tổng các hàng trong mỗi 3x3 slice):
[[42 27 28]
 [23 22 38]
 [33  5 26]]

Tổng theo 'sâu' (axis=0, tổng qua các slice 3x3):
[[26 13 20]
 [43 29 58]
 [29 12 14]]


In [21]:
#Cau13:
vector1 = np.random.rand(10)
vector2 = np.random.rand(10)

print("Vector 1:", vector1)
print("Vector 2:", vector2)

inner_product = np.dot(vector1, vector2)

print("\nInner product (tích vô hướng) của hai vector:", inner_product)

Vector 1: [0.99741979 0.04156088 0.4247998  0.13641591 0.61928513 0.87572271
 0.31007772 0.48426719 0.88886743 0.73783556]
Vector 2: [0.02946863 0.66746198 0.5010121  0.54861092 0.90986008 0.63465634
 0.8596683  0.56384413 0.70186815 0.58336147]

Inner product (tích vô hướng) của hai vector: 3.0579555628250725


In [22]:
!pip install pandas

In [24]:
#Cau14
A = np.random.randint(1, 10, size=(4, 3))
y = np.random.randint(1, 10, size=3)

print("Ma trận A:")
print(A)
print("\nVector y:")
print(y)

result_matrix = A + y

print("\nMa trận kết quả (A + y):")
print(result_matrix)

Ma trận A:
[[3 5 5]
 [7 6 9]
 [8 1 1]
 [2 5 4]]

Vector y:
[6 6 8]

Ma trận kết quả (A + y):
[[ 9 11 13]
 [13 12 17]
 [14  7  9]
 [ 8 11 12]]


In [27]:
#Cau15
import pandas as pd

series1 = pd.Series([2, 4, 6, 8, 10])
series2 = pd.Series([1, 3, 5, 7, 10])

print("Series 1:")
print(series1)
print("Series 2:")
print(series2)

cong_result = series1 + series2
print("\nKết quả Cộng:")
print(cong_result)

tru_result = series1 - series2
print("Kết quả Trừ:")
print(tru_result)

nhan_result = series1 * series2
print("Kết quả Nhân:")
print(nhan_result)

chia_result = series1 / series2
print("Kết quả Chia:")
print(chia_result)

Series 1:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Series 2:
0     1
1     3
2     5
3     7
4    10
dtype: int64

Kết quả Cộng:
0     3
1     7
2    11
3    15
4    20
dtype: int64
Kết quả Trừ:
0    1
1    1
2    1
3    1
4    0
dtype: int64
Kết quả Nhân:
0      2
1     12
2     30
3     56
4    100
dtype: int64
Kết quả Chia:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.000000
dtype: float64


In [32]:
#Cau16
data = {
    'Cột A': np.random.randint(1, 10, size=5),
    'Cột B': np.random.randint(10, 20, size=5),
    'Cột C': np.random.randint(20, 30, size=5)
}
df = pd.DataFrame(data)
print("DataFrame gốc:")
print(df)

first_column = df['Cột A']
print("\nCột đầu tiên dưới dạng Series:")
print(first_column)
print(f"Kiểu dữ liệu: {type(first_column)}")

DataFrame gốc:
   Cột A  Cột B  Cột C
0      3     11     25
1      6     10     27
2      6     12     25
3      1     11     25
4      4     12     23

Cột đầu tiên dưới dạng Series:
0    3
1    6
2    6
3    1
4    4
Name: Cột A, dtype: int64
Kiểu dữ liệu: <class 'pandas.core.series.Series'>


In [33]:
#Cau17
data = {
    'Cột X': np.random.randint(1, 100, size=4),
    'Cột Y': np.random.randint(1, 100, size=4),
    'Cột Z': np.random.randint(1, 100, size=4)
}
df_random = pd.DataFrame(data)

print("DataFrame gốc:")
print(df_random)

df_sorted_by_X = df_random.sort_values(by='Cột X')
print("\nDataFrame sau khi sắp xếp theo 'Cột X':")
print(df_sorted_by_X)

#giam dan
df_sorted_by_Y_desc = df_random.sort_values(by='Cột Y', ascending=False)
print("\nDataFrame sau khi sắp xếp theo 'Cột Y' (giảm dần):")
print(df_sorted_by_Y_desc)

DataFrame gốc:
   Cột X  Cột Y  Cột Z
0     66     74     89
1     82     85     54
2     92     14     81
3     79     86     25

DataFrame sau khi sắp xếp theo 'Cột X':
   Cột X  Cột Y  Cột Z
0     66     74     89
3     79     86     25
1     82     85     54
2     92     14     81

DataFrame sau khi sắp xếp theo 'Cột Y' (giảm dần):
   Cột X  Cột Y  Cột Z
3     79     86     25
1     82     85     54
0     66     74     89
2     92     14     81


In [34]:
#Cau18
s = pd.Series([10, 20, 30, 40, 50], index=['a', 'b', 'c', 'd', 'e'])
print("Series gốc:")
print(s)
new_index = ['c', 'a', 'x', 'd', 'f', 'e']

s_reindexed = s.reindex(new_index)

print("\nSeries sau khi reindex:")
print(s_reindexed)

Series gốc:
a    10
b    20
c    30
d    40
e    50
dtype: int64

Series sau khi reindex:
c    30.0
a    10.0
x     NaN
d    40.0
f     NaN
e    50.0
dtype: float64
