<a href="https://colab.research.google.com/github/hongocphuongnhu/TH_Deep_Learning/blob/main/TH_Deep_Tuan1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
!pip install numpy
import numpy as np

In [18]:
a = np.random.randint(20, size = (3,3))
print (a)
print("Kiểm tra các phần tử khác 0 trong mảng: ",np.all(a))
print("Kiểm tra có tồn tại ít nhất một phần tử khác 0 trong mảng: ", np.any(a))

[[14  1  3]
 [ 9 19  2]
 [10  9  6]]
Kiểm tra các phần tử khác 0 trong mảng:  True
Kiểm tra có tồn tại ít nhất một phần tử khác 0 trong mảng:  True


In [ ]:
arr1_1c = np.randint()